pipeline {
    agent any

    environment {
    SVC_ACCOUNT_KEY = credentials('terraform-auth')
  }
     
    stages {
              stage ('checkout'){
            steps {
                git branch: 'main', url: 'https://github.com/rohitnaidu911/GCP.git'
            }
        }
		stage('Set creds') {
            steps {
              
                sh 'echo $SVC_ACCOUNT_KEY | base64 -d > ./google-compute-engine/jenkins.json'
		            sh 'pwd'
                       
               
            }
        }

	
	stage('Auth-Project') {
	 steps {
		 dir('google-compute-engine')
		 {
    
        sh 'gcloud auth activate-service-account jenkins@mi-dev-lab.iam.gserviceaccount.com --key-file=jenkins.json'
    }
    }
	}
 	 
	stage('Create Instance') {
	 steps {
    
    sh 'gcloud compute instances create $VM_NAME --zone=$ZONE --machine-type=n1-standard-2 --tags=http-server,https-server --create-disk=auto-delete=yes,boot=yes,device-name=rohit-instance3,image=projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20221018,mode=rw,size=10,type=projects/mi-uat-lab/zones/europe-west2-a/diskTypes/pd-balanced --metadata-from-file=startup-script=./google-compute-engine/startup-script.sh'
        
    }
    }
    
    	stage('Collect External IP') {
	 steps {
    
         sh "gcloud compute instances describe $VM_NAME --zone=$ZONE --format='get(networkInterfaces[0].accessConfigs[0].natIP)' > ip.txt"
	     sh 'cat ip.txt'
        
    }
    }
    
    
  
    stage('App health check') {
	 steps {
            sh 'sleep 90'
	    sh 'curl http://$(cat ip.txt)'
    
    }
    }
   }
}
